### ISSUE TITLE
Orbit Tooltip

### ISSUE THREAD

**Issue by RichardIvan** [kiwicom/eslint-plugin-kiwicom#31]
Always include `closeText` when using Orbit's Tooltip, as we always want to have the close button on mobile viewport translated.

https://github.com/kiwicom/orbit-components/tree/master/src/Tooltip

**Comment by flanzana** [comment]
Orbit removed `closeText` prop from Tooltip (in version 0.40) because they will automatically handle translations, so I guess this issue can be closed.

https://orbit.kiwi/components/tooltip/
